/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package others;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Ronzeyt
 */
public class copyDefination extends javax.swing.JFrame {

    /**
     * Creates new form apple
     */
    public copyDefination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerjPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        subHeaderLabel = new javax.swing.JLabel();
        itemDefinejPanel = new javax.swing.JPanel();
        namejLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        uidjLabel = new javax.swing.JLabel();
        dataTypejLabel = new javax.swing.JLabel();
        uidjTextField = new javax.swing.JTextField();
        addItemButton = new javax.swing.JButton();
        addItemReset = new javax.swing.JButton();
        dataTypejPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        formulaDefinejPanel = new javax.swing.JPanel();
        formulateItemjLabel = new javax.swing.JLabel();
        formulateItemChoice = new java.awt.Choice();
        jScrollPane1 = new javax.swing.JScrollPane();
        FormulaDefinejTextArea = new javax.swing.JTextArea();
        addFormulaButton = new javax.swing.JButton();
        formulaResetButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        lowerViewjPanel = new javax.swing.JPanel();
        ViewDefinedItems = new javax.swing.JButton();
        viewDefinedFormula = new javax.swing.JButton();
        footerjPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        statusBarjPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusBarjTextArea = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("National Insurance Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        headerjPanel.setBackground(new java.awt.Color(102, 102, 102));
        headerjPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        headerLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(240, 240, 240));
        headerLabel.setText("National Insurance Management System");

        subHeaderLabel.setForeground(new java.awt.Color(240, 240, 240));
        subHeaderLabel.setText("Test Prototype (Version 1.0)");

        javax.swing.GroupLayout headerjPanelLayout = new javax.swing.GroupLayout(headerjPanel);
        headerjPanel.setLayout(headerjPanelLayout);
        headerjPanelLayout.setHorizontalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subHeaderLabel))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        headerjPanelLayout.setVerticalGroup(
            headerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerjPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subHeaderLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        itemDefinejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Item Defination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        namejLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        namejLabel.setText("Name:");

        namejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextFieldActionPerformed(evt);
            }
        });

        uidjLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        uidjLabel.setText("UID:");

        dataTypejLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        dataTypejLabel.setText("Data Type:");

        uidjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidjTextFieldActionPerformed(evt);
            }
        });

        addItemButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addItemButton.setText("Add Item");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });

        addItemReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addItemReset.setText("Reset");
        addItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemResetActionPerformed(evt);
            }
        });

        dataTypejPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRadioButton1.setText("User Input");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Calculate");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Formulate");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataTypejPanelLayout = new javax.swing.GroupLayout(dataTypejPanel);
        dataTypejPanel.setLayout(dataTypejPanelLayout);
        dataTypejPanelLayout.setHorizontalGroup(
            dataTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataTypejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dataTypejPanelLayout.setVerticalGroup(
            dataTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataTypejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2)
                .addComponent(jRadioButton3))
        );

        javax.swing.GroupLayout itemDefinejPanelLayout = new javax.swing.GroupLayout(itemDefinejPanel);
        itemDefinejPanel.setLayout(itemDefinejPanelLayout);
        itemDefinejPanelLayout.setHorizontalGroup(
            itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDefinejPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDefinejPanelLayout.createSequentialGroup()
                        .addComponent(dataTypejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDefinejPanelLayout.createSequentialGroup()
                        .addGroup(itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, itemDefinejPanelLayout.createSequentialGroup()
                                .addComponent(namejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(namejTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, itemDefinejPanelLayout.createSequentialGroup()
                                .addComponent(uidjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uidjTextField))
                            .addComponent(dataTypejPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, itemDefinejPanelLayout.createSequentialGroup()
                                .addComponent(addItemButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))))
        );
        itemDefinejPanelLayout.setVerticalGroup(
            itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDefinejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uidjLabel)
                    .addComponent(uidjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataTypejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataTypejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itemDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItemReset)
                    .addComponent(addItemButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formulaDefinejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Formula Defination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        formulateItemjLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        formulateItemjLabel.setText("Formulate Item:");

        FormulaDefinejTextArea.setColumns(20);
        FormulaDefinejTextArea.setRows(5);
        jScrollPane1.setViewportView(FormulaDefinejTextArea);

        addFormulaButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addFormulaButton.setText("Add Formula");
        addFormulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFormulaButtonActionPerformed(evt);
            }
        });

        formulaResetButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formulaResetButton.setText("Reset");
        formulaResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaResetButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Please specify the formula steps for the selected item:");

        javax.swing.GroupLayout formulaDefinejPanelLayout = new javax.swing.GroupLayout(formulaDefinejPanel);
        formulaDefinejPanel.setLayout(formulaDefinejPanelLayout);
        formulaDefinejPanelLayout.setHorizontalGroup(
            formulaDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formulaDefinejPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(formulaDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulaDefinejPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(369, Short.MAX_VALUE))
                    .addGroup(formulaDefinejPanelLayout.createSequentialGroup()
                        .addGroup(formulaDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formulaDefinejPanelLayout.createSequentialGroup()
                                .addComponent(formulateItemjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formulateItemChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(formulaDefinejPanelLayout.createSequentialGroup()
                                .addComponent(addFormulaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formulaResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(21, 21, 21))))
        );
        formulaDefinejPanelLayout.setVerticalGroup(
            formulaDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formulaDefinejPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(formulaDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formulateItemChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formulateItemjLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formulaDefinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFormulaButton)
                    .addComponent(formulaResetButton))
                .addContainerGap())
        );

        lowerViewjPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ViewDefinedItems.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ViewDefinedItems.setText("View Defined Items");
        ViewDefinedItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDefinedItemsActionPerformed(evt);
            }
        });

        viewDefinedFormula.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        viewDefinedFormula.setText("View Defined Formulas");
        viewDefinedFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDefinedFormulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lowerViewjPanelLayout = new javax.swing.GroupLayout(lowerViewjPanel);
        lowerViewjPanel.setLayout(lowerViewjPanelLayout);
        lowerViewjPanelLayout.setHorizontalGroup(
            lowerViewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerViewjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewDefinedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewDefinedFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lowerViewjPanelLayout.setVerticalGroup(
            lowerViewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerViewjPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(lowerViewjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewDefinedItems)
                    .addComponent(viewDefinedFormula))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        footerjPanel.setBackground(new java.awt.Color(102, 102, 102));
        footerjPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerjPanelLayout = new javax.swing.GroupLayout(footerjPanel);
        footerjPanel.setLayout(footerjPanelLayout);
        footerjPanelLayout.setHorizontalGroup(
            footerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerjPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(goBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        footerjPanelLayout.setVerticalGroup(
            footerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(goBackButton)
                    .addComponent(homeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        helpButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        helpButton.setText("Help");

        statusBarjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Status Bar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        statusBarjTextArea.setEditable(false);
        statusBarjTextArea.setColumns(20);
        statusBarjTextArea.setRows(5);
        jScrollPane2.setViewportView(statusBarjTextArea);

        javax.swing.GroupLayout statusBarjPanelLayout = new javax.swing.GroupLayout(statusBarjPanel);
        statusBarjPanel.setLayout(statusBarjPanelLayout);
        statusBarjPanelLayout.setHorizontalGroup(
            statusBarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(statusBarjPanelLayout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        statusBarjPanelLayout.setVerticalGroup(
            statusBarjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusBarjPanelLayout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerjPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowerViewjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusBarjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemDefinejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formulaDefinejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(972, Short.MAX_VALUE)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formulaDefinejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemDefinejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusBarjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerViewjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(footerjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_exitButtonActionPerformed

    Timer timer = new Timer(5000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                headerLabel.setVisible(false);
            }
        });    
         
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
       /* itemDefinejPanel.setVisible(false);
        formulaDefinejPanel.setVisible(false);
        statusBarjPanel.setVisible(false);
        lowerViewjPanel.setVisible(false);
        helpButton.setVisible(false);
        */
        
       // NewJFrame a = new NewJFrame();
        //a.setVisible(true);
        
        
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:
        itemDefinejPanel.setVisible(true);
        formulaDefinejPanel.setVisible(true);
        statusBarjPanel.setVisible(true);
        lowerViewjPanel.setVisible(true);
        helpButton.setVisible(true);
        
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void viewDefinedFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDefinedFormulaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_viewDefinedFormulaActionPerformed

    private void ViewDefinedItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDefinedItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewDefinedItemsActionPerformed

    private void formulaResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulaResetButtonActionPerformed
        Component frame = null;
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(frame,"Sorry,The required bicycle is not available.","ERROR",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_formulaResetButtonActionPerformed

    private void addFormulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFormulaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFormulaButtonActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected() || jRadioButton2.isSelected()){
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected() || jRadioButton3.isSelected()){
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2.isSelected() || jRadioButton3.isSelected()){
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void addItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemResetActionPerformed
        // TODO add your handling code here:
        headerLabel.setVisible(false);
    }//GEN-LAST:event_addItemResetActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        headerLabel.setVisible(true);
        timer.start();
        headerLabel.setText("Apple");
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void uidjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidjTextFieldActionPerformed

    private void namejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new copyDefination().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FormulaDefinejTextArea;
    private javax.swing.JButton ViewDefinedItems;
    private javax.swing.JButton addFormulaButton;
    private javax.swing.JButton addItemButton;
    private javax.swing.JButton addItemReset;
    private javax.swing.JLabel dataTypejLabel;
    private javax.swing.JPanel dataTypejPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel footerjPanel;
    private javax.swing.JPanel formulaDefinejPanel;
    private javax.swing.JButton formulaResetButton;
    private java.awt.Choice formulateItemChoice;
    private javax.swing.JLabel formulateItemjLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerjPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel itemDefinejPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lowerViewjPanel;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JPanel statusBarjPanel;
    private javax.swing.JTextArea statusBarjTextArea;
    private javax.swing.JLabel subHeaderLabel;
    private javax.swing.JLabel uidjLabel;
    private javax.swing.JTextField uidjTextField;
    private javax.swing.JButton viewDefinedFormula;
    // End of variables declaration//GEN-END:variables
}