/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.nationalinsurance.gui;

import com.nationalinsurance.services.CalculationService;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronzeyt
 */
public class FormulaCalculationGUI extends javax.swing.JPanel{
    private CardLayoutInterface cardlayout;
    private int textFieldCount;
    private  ArrayList<String> inputUIDs;
    private HashMap<Integer,javax.swing.JTextField> textFieldMap;
    private javax.swing.JTextField answer;   //making this a class attribute so that the calculated value can be set in actionperformed.
    /**
     * Creates new form MainPanelGUI
     * @param cardlayout
     */
    public FormulaCalculationGUI(CardLayoutInterface cardlayout) {
        initComponents();
        this.cardlayout = cardlayout;
        textFieldCount = 0;
        inputUIDs = new ArrayList<>();      //initializing in constructor so that it can used in actionlistener        
        textFieldMap = new HashMap<>();     //for storing textfield   
        answer = null;
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        AddDefinationLabel = new javax.swing.JLabel();
        ViewItemLabel = new javax.swing.JLabel();
        ViewFormulaLabel = new javax.swing.JLabel();
        FormulaPanel = new javax.swing.JPanel();
        FormulaScrollPane = new javax.swing.JScrollPane();
        MainFormulaPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(850, 520));

        SidePanel.setBackground(new java.awt.Color(255, 255, 255));
        SidePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item/Formula Defination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        AddDefinationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddDefinationLabel.setForeground(new java.awt.Color(0, 153, 0));
        AddDefinationLabel.setText("Add New Defination");
        AddDefinationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddDefinationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDefinationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddDefinationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddDefinationLabelMouseExited(evt);
            }
        });

        ViewItemLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewItemLabel.setForeground(new java.awt.Color(0, 153, 0));
        ViewItemLabel.setText("View Items");
        ViewItemLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewItemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewItemLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewItemLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewItemLabelMouseExited(evt);
            }
        });

        ViewFormulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewFormulaLabel.setForeground(new java.awt.Color(0, 153, 0));
        ViewFormulaLabel.setText("View Formulas");
        ViewFormulaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFormulaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewFormulaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewFormulaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewFormulaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewFormulaLabel)
                    .addComponent(ViewItemLabel)
                    .addComponent(AddDefinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(AddDefinationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewItemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewFormulaLabel)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        FormulaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)), "Formula Calculatation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        FormulaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        MainFormulaPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainFormulaPanel.setAutoscrolls(true);

        javax.swing.GroupLayout MainFormulaPanelLayout = new javax.swing.GroupLayout(MainFormulaPanel);
        MainFormulaPanel.setLayout(MainFormulaPanelLayout);
        MainFormulaPanelLayout.setHorizontalGroup(
            MainFormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );
        MainFormulaPanelLayout.setVerticalGroup(
            MainFormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        MainFormulaPanel.setLayout(null);
        FormulaScrollPane.setViewportView(MainFormulaPanel);

        javax.swing.GroupLayout FormulaPanelLayout = new javax.swing.GroupLayout(FormulaPanel);
        FormulaPanel.setLayout(FormulaPanelLayout);
        FormulaPanelLayout.setHorizontalGroup(
            FormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormulaPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(FormulaScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        FormulaPanelLayout.setVerticalGroup(
            FormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulaPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(FormulaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FormulaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormulaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddDefinationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDefinationLabelMouseClicked
        // TODO add your handling code here:
        cardlayout.setBackButtonValue("mainPanelCard");
        cardlayout.show("definationCard");
        cardlayout.displayBackButton(true);
    }//GEN-LAST:event_AddDefinationLabelMouseClicked

    private void AddDefinationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDefinationLabelMouseEntered
        // TODO add your handling code here:
        AddDefinationLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        AddDefinationLabel.revalidate();
        AddDefinationLabel.repaint();
    }//GEN-LAST:event_AddDefinationLabelMouseEntered

    private void AddDefinationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDefinationLabelMouseExited
        // TODO add your handling code here:
        AddDefinationLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        AddDefinationLabel.revalidate();
        AddDefinationLabel.repaint();
    }//GEN-LAST:event_AddDefinationLabelMouseExited

    private void ViewItemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemLabelMouseClicked
        // TODO add your handling code here:
        cardlayout.setBackButtonValue("mainPanelCard");
        cardlayout.show("listItemCard");
        cardlayout.displayBackButton(true);
    }//GEN-LAST:event_ViewItemLabelMouseClicked

    private void ViewItemLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemLabelMouseEntered
        // TODO add your handling code here:
        ViewItemLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        ViewItemLabel.revalidate();
        ViewItemLabel.repaint();
    }//GEN-LAST:event_ViewItemLabelMouseEntered

    private void ViewItemLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemLabelMouseExited
        // TODO add your handling code here:
        ViewItemLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ViewItemLabel.revalidate();
        ViewItemLabel.repaint();
    }//GEN-LAST:event_ViewItemLabelMouseExited

    private void ViewFormulaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFormulaLabelMouseClicked
        // TODO add your handling code here:
        cardlayout.setBackButtonValue("mainPanelCard");
        cardlayout.show("listFormulaCard");
        cardlayout.displayBackButton(true);
    }//GEN-LAST:event_ViewFormulaLabelMouseClicked

    private void ViewFormulaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFormulaLabelMouseEntered
        // TODO add your handling code here:
        ViewFormulaLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        ViewFormulaLabel.revalidate();
        ViewFormulaLabel.repaint();
    }//GEN-LAST:event_ViewFormulaLabelMouseEntered

    private void ViewFormulaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFormulaLabelMouseExited
        // TODO add your handling code here:
        ViewFormulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ViewFormulaLabel.revalidate();
        ViewFormulaLabel.repaint();
    }//GEN-LAST:event_ViewFormulaLabelMouseExited
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDefinationLabel;
    private javax.swing.JPanel FormulaPanel;
    private javax.swing.JScrollPane FormulaScrollPane;
    private javax.swing.JPanel MainFormulaPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel ViewFormulaLabel;
    private javax.swing.JLabel ViewItemLabel;
    // End of variables declaration//GEN-END:variables

    
    public void formulaCalculatePage(final String uid){     //using final so that it can be used in actionlistener
        MainFormulaPanel.removeAll();
        
        CalculationService calculationService = new CalculationService();
        String name = calculationService.getFormulateName(uid);     //getting the name of the UID        
        inputUIDs = calculationService.getInputItems(uid);
               
        textFieldCount = inputUIDs.size();  //setting the count of textfield which is later used to get textfield value in calculateFormula() method
            
        javax.swing.JLabel title = new javax.swing.JLabel();
        title.setText(name+"("+uid+")");
        MainFormulaPanel.add(title);
        title.setBounds(250,30,400,20);
        title.setFont(new java.awt.Font("Verdana", 1, 13));
        title.setForeground(Color.red);
            
        int height = 70;
        int length = 100;
        for (int i=0;i<inputUIDs.size();i++) {
            javax.swing.JLabel label = new javax.swing.JLabel();
            label.setText(inputUIDs.get(i));
            label.setFont(new java.awt.Font("Verdana", 1, 11));
            
            javax.swing.JLabel divider = new javax.swing.JLabel(" : ");
            
            javax.swing.JTextField text = new javax.swing.JTextField();
            text.setName(inputUIDs.get(i));     //useful in error alert eg. this item text field is empty
            textFieldMap.put(i, text);
            
            MainFormulaPanel.add(label);
            label.setBounds(length,height,200,22);
            
            MainFormulaPanel.add(divider);
            divider.setBounds(length+205,height,10,22);
            
            MainFormulaPanel.add(text);            
            text.setBounds(length+220,height,250,22);
            
            height = height+30;
        }
        javax.swing.JButton submit = new javax.swing.JButton("Calculate");
        answer = new javax.swing.JTextField();
        javax.swing.JButton reset = new javax.swing.JButton("Reset");
        
        MainFormulaPanel.add(submit);            
        submit.setBounds(100,height+20,200,25);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setFont(new java.awt.Font("Verdana", 1, 12));
        submit.setForeground(Color.blue);
        submit.setFocusable(false);
           
        MainFormulaPanel.add(answer);            
        answer.setBounds(320,height+20,250,25);
        //answer.setEnabled(true);
        answer.setFocusable(false);
        answer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        answer.setFont(new java.awt.Font("Verdana", 1, 12));
        answer.setForeground(Color.red);
        
        MainFormulaPanel.add(reset);
        reset.setBounds(500,height+50,70,15);
        reset.setFont(new java.awt.Font("Verdana", 0, 9));
        
        reset.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    for (int k=0;k<textFieldMap.size();k++){
                        textFieldMap.get(k).setText("");
                    }
                    answer.setText("");
                }
        });
                
        submit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    HashMap<String,Double> list = new HashMap<>(); 
                    boolean status = false;
                    for(int i=0; i<textFieldCount;i++){ 
                        try{
                        double value =Double.parseDouble(textFieldMap.get(i).getText());
                        }
                        catch (NumberFormatException e){ 
                            JOptionPane.showMessageDialog(null, "Calculation denied!\nYou must enter non-empty and numeric values.","INVALID",JOptionPane.INFORMATION_MESSAGE);
                            
                            status = false;
                            break;
                        }                        
                        if (textFieldMap.get(i).getText().equals("")){
                            JOptionPane.showMessageDialog(null, "Please enter valid textfield value.","Invalid Value",JOptionPane.INFORMATION_MESSAGE);
                            status = false;
                            break;
                        }
                        else{
                            int index1 = inputUIDs.get(i).indexOf("(");
                            int index2 = inputUIDs.get(i).indexOf(")");
                            String uid = inputUIDs.get(i).substring(index1+1,index2);
                            list.put(uid, Double.parseDouble(textFieldMap.get(i).getText()));
                            status = true;
                        }
                    }
                    if (status==true){
                        CalculationService calculation = new CalculationService();
                        double totalValue = calculation.calculateFormula(list,uid);   //calculating the formula
                        answer.setText(Double.toString(totalValue));
                    }
                }
            });
        
        MainFormulaPanel.revalidate();
        MainFormulaPanel.repaint();
        cardlayout.setBackButtonValue("mainPanelCard");
    }   
}
