/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.nationalinsurance.gui;

/**
 *
 * @author Ronzeyt
 */
public class MainGUI extends javax.swing.JFrame implements CardLayoutInterface{
   //used to store backbutton value. used when called goBack button. value is each jpanel card name;
    private String backButtonValue; 
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        //HomeButton.setVisible(false);
        GoBackButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        TitleLabel = new javax.swing.JLabel();
        SubTitleLabel = new javax.swing.JLabel();
        OpenNewWindow = new javax.swing.JLabel();
        MainBodyPanel = new javax.swing.JPanel();
        FooterPanel = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        GoBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("National Insurance Management System");
        setExtendedState(getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        setName("MainFrame"); // NOI18N

        HeaderPanel.setBackground(new java.awt.Color(102, 102, 102));
        HeaderPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TitleLabel.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(240, 240, 240));
        TitleLabel.setText("National Insurance Management System");

        SubTitleLabel.setForeground(new java.awt.Color(240, 240, 240));
        SubTitleLabel.setText("Test Prototype (Version 1.0)");

        OpenNewWindow.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OpenNewWindow.setForeground(new java.awt.Color(255, 255, 255));
        OpenNewWindow.setText("Open new Window");
        OpenNewWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenNewWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenNewWindowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OpenNewWindowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OpenNewWindowMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanelLayout.createSequentialGroup()
                        .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                        .addComponent(SubTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OpenNewWindow)))
                .addContainerGap())
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SubTitleLabel)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OpenNewWindow)
                .addGap(11, 11, 11))
        );

        MainBodyPanel.setPreferredSize(new java.awt.Dimension(850, 520));
        MainBodyPanel.setLayout(new java.awt.CardLayout());

        FooterPanel.setBackground(new java.awt.Color(102, 102, 102));
        FooterPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitButton.setFocusPainted(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        GoBackButton.setText("Go Back");
        GoBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GoBackButton.setFocusPainted(false);
        GoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GoBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(GoBackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //Adding main panel gui in card layout
        mainPanelGUI = new MainPanelGUI(this);
        MainBodyPanel.add(mainPanelGUI, "mainPanelCard");

        //Adding defination GUI in card layout
        definationGUI = new DefinationGUI(this);
        MainBodyPanel.add(definationGUI, "definationCard");

        //Adding calculate formula page in main panel
        calculateGUI = new FormulaCalculationGUI(this);
        MainBodyPanel.add(calculateGUI, "calculateCard");

        //Adding list item panel in card layout
        listItemGUI = new ListItemsGUI(this);
        MainBodyPanel.add(listItemGUI, "listItemCard");

        //Adding list formula panel in card layout
        listFormulaGUI = new ListFormulaGUI(this);
        MainBodyPanel.add(listFormulaGUI, "listFormulaCard");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackButtonActionPerformed
        // TODO add your handling code here:
        /*java.awt.CardLayoutInterface card = (java.awt.CardLayoutInterface)MainBodyPanel.getLayout();
        card.previous(MainBodyPanel);*/
        System.out.println(backButtonValue);
        this.show(backButtonValue);
        
        if (backButtonValue=="definationCard"){            
            backButtonValue = "mainPanelCard";
        }        
        else if (backButtonValue=="mainPanelCard"){
            //HomeButton.setVisible(false);
            GoBackButton.setVisible(false);
            
            //to update mainpanel formula list when new item is added in the defination page
            mainPanelGUI.updateUI();
        }
    }//GEN-LAST:event_GoBackButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void OpenNewWindowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenNewWindowMouseEntered
        // TODO add your handling code here:
        OpenNewWindow.setFont(new java.awt.Font("Tahoma", 1, 11));
        OpenNewWindow.revalidate();
        OpenNewWindow.repaint();
    }//GEN-LAST:event_OpenNewWindowMouseEntered

    private void OpenNewWindowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenNewWindowMouseExited
        // TODO add your handling code here:
        OpenNewWindow.setFont(new java.awt.Font("Tahoma", 0, 12));
        OpenNewWindow.revalidate();
        OpenNewWindow.repaint();
    }//GEN-LAST:event_OpenNewWindowMouseExited

    private void OpenNewWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenNewWindowMouseClicked
        // TODO add your handling code here:
        MainGUI newWindow = new MainGUI();
        newWindow.setVisible(true);
    }//GEN-LAST:event_OpenNewWindowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JButton GoBackButton;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MainBodyPanel;
    private MainPanelGUI mainPanelGUI;
    private DefinationGUI definationGUI;
    private FormulaCalculationGUI calculateGUI;
    private ListItemsGUI listItemGUI;
    private ListFormulaGUI listFormulaGUI;
    private javax.swing.JLabel OpenNewWindow;
    private javax.swing.JLabel SubTitleLabel;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables

    //this is a show() method to navigate to different pages
    @Override
    public void show(String cardName){
        
        //for the purpose of pre-selecting uid in formula choice list if formula defination section is accessed from mainpanel jOption option.
        int index=0;
        String card = "";
        String uid = "";
        if(cardName.contains("+")){
            index=cardName.indexOf("+");
            card=cardName.substring(0, index);
            uid=cardName.substring(index+1); 
            //changing the choice list item to the selected item.
            definationGUI.changeFormulaDefPanelStatus(uid);
            
            java.awt.CardLayout cardlayout = (java.awt.CardLayout)MainBodyPanel.getLayout();
            cardlayout.show(MainBodyPanel, card);  
            displayBackButton(true);
        }
        
        //this option triggered if the cardname contain # symbol. 
        //this option is used to open formula calculation GUI. the cardname also contains the UID of the item that needs to be calculated
        else if(cardName.contains("#")){
            index=cardName.indexOf("#");
            card=cardName.substring(0, index);
            uid=cardName.substring(index+1); 
            //changing the choice list item to the selected item.
            //definationGUI.changeFormulaDefPanelStatus(uid);
            
            calculateGUI.formulaCalculatePage(uid);         //calling calculateGUI method to add formula input components
            
            java.awt.CardLayout cardlayout = (java.awt.CardLayout)MainBodyPanel.getLayout();
            cardlayout.show(MainBodyPanel, card);  
            displayBackButton(true);
        }
        //normal navigation between cards
        else{
            java.awt.CardLayout cardlayout = (java.awt.CardLayout)MainBodyPanel.getLayout();
            cardlayout.show(MainBodyPanel, cardName);
        }
    }
    /*
    @Override
    public void displayHomeButton(boolean status){
        HomeButton.setVisible(status);
    }
    */
    
    @Override
    public void displayBackButton(boolean status){
        GoBackButton.setVisible(status);
    }
    
    @Override
    public String getBackButtonValue(){
        return backButtonValue;
    }
    
    @Override
    public void setBackButtonValue(String backButtonValue){
        this.backButtonValue = backButtonValue;        
    }
}
