/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.nationalinsurance.gui;

import com.nationalinsurance.services.CalculationService;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronzeyt
 */
public class MainPanelGUI extends javax.swing.JPanel{
    private CardLayoutInterface cardlayout;
    /**
     * Creates new form MainPanelGUI
     * @param cardlayout
     */
    public MainPanelGUI(CardLayoutInterface cardlayout) {
        initComponents();
        this.cardlayout = cardlayout;
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        AddDefinationLabel = new javax.swing.JLabel();
        ViewItemLabel = new javax.swing.JLabel();
        ViewFormulaLabel = new javax.swing.JLabel();
        FormulaPanel = new javax.swing.JPanel();
        FormulaScrollPane = new javax.swing.JScrollPane();
        MainFormulaPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(850, 520));

        SidePanel.setBackground(new java.awt.Color(255, 255, 255));
        SidePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item/Formula Defination", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        AddDefinationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AddDefinationLabel.setForeground(new java.awt.Color(0, 153, 0));
        AddDefinationLabel.setText("Add New Defination");
        AddDefinationLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddDefinationLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddDefinationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddDefinationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddDefinationLabelMouseExited(evt);
            }
        });

        ViewItemLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewItemLabel.setForeground(new java.awt.Color(0, 153, 0));
        ViewItemLabel.setText("View Items");
        ViewItemLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewItemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewItemLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewItemLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewItemLabelMouseExited(evt);
            }
        });

        ViewFormulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewFormulaLabel.setForeground(new java.awt.Color(0, 153, 0));
        ViewFormulaLabel.setText("View Formulas");
        ViewFormulaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFormulaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewFormulaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewFormulaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewFormulaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewFormulaLabel)
                    .addComponent(ViewItemLabel)
                    .addComponent(AddDefinationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(AddDefinationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewItemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewFormulaLabel)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        FormulaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)), "Functions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        FormulaScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        MainFormulaPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainFormulaPanel.setAutoscrolls(true);

        javax.swing.GroupLayout MainFormulaPanelLayout = new javax.swing.GroupLayout(MainFormulaPanel);
        MainFormulaPanel.setLayout(MainFormulaPanelLayout);
        MainFormulaPanelLayout.setHorizontalGroup(
            MainFormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        MainFormulaPanelLayout.setVerticalGroup(
            MainFormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        MainFormulaPanel.setLayout(null);
        FormulaScrollPane.setViewportView(MainFormulaPanel);
        formulaItemDisplayPanel();

        jButton1.setText("Refresh");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("(Refresh, if you don't see recently added Formula Items)");

        javax.swing.GroupLayout FormulaPanelLayout = new javax.swing.GroupLayout(FormulaPanel);
        FormulaPanel.setLayout(FormulaPanelLayout);
        FormulaPanelLayout.setHorizontalGroup(
            FormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormulaScrollPane)
            .addGroup(FormulaPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        FormulaPanelLayout.setVerticalGroup(
            FormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulaPanelLayout.createSequentialGroup()
                .addGroup(FormulaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormulaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FormulaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormulaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    //The below three action event are for Adddefination text to make clickable
    
    private void AddDefinationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDefinationLabelMouseEntered
        // TODO add your handling code here:
        AddDefinationLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        AddDefinationLabel.revalidate();
        AddDefinationLabel.repaint();
    }//GEN-LAST:event_AddDefinationLabelMouseEntered

    private void AddDefinationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDefinationLabelMouseClicked
        // TODO add your handling code here:
        cardlayout.setBackButtonValue("mainPanelCard");
         cardlayout.show("definationCard");
         cardlayout.displayBackButton(true);
    }//GEN-LAST:event_AddDefinationLabelMouseClicked

    private void AddDefinationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddDefinationLabelMouseExited
        // TODO add your handling code here:
        AddDefinationLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        AddDefinationLabel.revalidate();
        AddDefinationLabel.repaint();
    }//GEN-LAST:event_AddDefinationLabelMouseExited

    private void ViewItemLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemLabelMouseEntered
        // TODO add your handling code here:
        ViewItemLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        ViewItemLabel.revalidate();
        ViewItemLabel.repaint();
    }//GEN-LAST:event_ViewItemLabelMouseEntered

    private void ViewItemLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemLabelMouseExited
        // TODO add your handling code here:
        ViewItemLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ViewItemLabel.revalidate();
        ViewItemLabel.repaint();
    }//GEN-LAST:event_ViewItemLabelMouseExited

    private void ViewItemLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemLabelMouseClicked
        // TODO add your handling code here:
        cardlayout.setBackButtonValue("mainPanelCard");
        cardlayout.show("listItemCard");
        cardlayout.displayBackButton(true);
    }//GEN-LAST:event_ViewItemLabelMouseClicked

    private void ViewFormulaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFormulaLabelMouseEntered
        // TODO add your handling code here:
        ViewFormulaLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
        ViewFormulaLabel.revalidate();
        ViewFormulaLabel.repaint();
    }//GEN-LAST:event_ViewFormulaLabelMouseEntered

    private void ViewFormulaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFormulaLabelMouseExited
        // TODO add your handling code here:
        ViewFormulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12));
        ViewFormulaLabel.revalidate();
        ViewFormulaLabel.repaint();
    }//GEN-LAST:event_ViewFormulaLabelMouseExited

    private void ViewFormulaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFormulaLabelMouseClicked
        // TODO add your handling code here:
        cardlayout.setBackButtonValue("mainPanelCard");
        cardlayout.show("listFormulaCard");
        cardlayout.displayBackButton(true);
    }//GEN-LAST:event_ViewFormulaLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        formulaItemDisplayPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddDefinationLabel;
    private javax.swing.JPanel FormulaPanel;
    private javax.swing.JScrollPane FormulaScrollPane;
    private javax.swing.JPanel MainFormulaPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JLabel ViewFormulaLabel;
    private javax.swing.JLabel ViewItemLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
    public void formulaItemDisplayPanel(){
        MainFormulaPanel.removeAll();
        CalculationService calculationService = new CalculationService();
        ArrayList<String> items = new ArrayList<>();
        items = calculationService.getFormulateItems();
        if(items.size()==0){
            javax.swing.JLabel label = new javax.swing.JLabel();
            label.setText("Currently, formulas are not available. You can add new from the Defination Section.");
                label.setFont(new java.awt.Font("Verdana", 0, 11));
                MainFormulaPanel.add(label);
                label.setBounds(220,200,600,22);
        }
        else{
            int length=0;
            int height =30;
            for(int i=2; i<items.size()+2;i++){
                javax.swing.JButton formulateItem = new javax.swing.JButton(items.get(i-2));
                formulateItem.setFont(new java.awt.Font("Verdana", 0, 12));
                formulateItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                formulateItem.setForeground(Color.blue);
                formulateItem.setFocusable(false);
                formulateItem.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        getCalculatePage(evt);
                    }
                });
                MainFormulaPanel.add(formulateItem);  
                if (i%2==0){
                    length = 125;
                }
                else{
                    length = 525;
                }
                formulateItem.setBounds(length,height,350,28);
                if (i%2==0){
                    height = height;
                }
                else{
                    height = height+40;
                }
            }
        }
    }
    
    //this method navigate to selected formula item entry page
    private void getCalculatePage(java.awt.event.ActionEvent evt){
        javax.swing.JButton button = (javax.swing.JButton)evt.getSource();
        String buttonName =button.getText();
        
        int index1 = buttonName.indexOf("(");
        int index2 = buttonName.indexOf(")");
        String uid = buttonName.substring(index1+1, index2); 
       if (buttonName.contains("undefined")){
            int message = JOptionPane.showConfirmDialog(null,"Undefined Formula!\nWould you like to add Formula Steps Now?","FORMULA UNDEFINED",JOptionPane.YES_NO_OPTION);
            if(message==JOptionPane.YES_OPTION){
                cardlayout.show("definationCard+"+uid);  
                //cardlayout.setBackButtonValue("definationCard");
            }
       }       
        else{
            cardlayout.show("calculateCard#"+uid);  
        }
    }
}
